-- =============================================================================
-- ERP RESTAURANTE BRASILEIRINHO
-- Banco de dados: BRASILEIRINHO  (PostgreSQL 14+)
-- Padrão de nomenclatura: snake_case  +  sufixo da entidade nas colunas
-- Estrutura: 14 tabelas em 3ª Forma Normal
-- =============================================================================

CREATE DATABASE "BRASILEIRINHO"
    WITH ENCODING = 'UTF8' TEMPLATE = template0;

\connect "BRASILEIRINHO"


-- =============================================================================
-- 1. HIERARQUIA GEOGRÁFICA
-- =============================================================================

CREATE TABLE pais (
    id_pais                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_pais                varchar(100) NOT NULL,
    codigo_pais              varchar(5),
    sigla_pais               varchar(5),
    nacionalidade_pais       varchar(100),
    data_cadastro_pais       timestamp with time zone NOT NULL DEFAULT now(),
    ultima_modificacao_pais  timestamp with time zone NOT NULL DEFAULT now(),
    ativo_pais               boolean NOT NULL DEFAULT TRUE
);

CREATE TABLE estado (
    id_estado                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_estado                varchar(100) NOT NULL,
    uf_estado                  varchar(2)   NOT NULL,
    pais_id                    bigint REFERENCES pais(id_pais),
    data_cadastro_estado       timestamp with time zone NOT NULL DEFAULT now(),
    ultima_modificacao_estado  timestamp with time zone NOT NULL DEFAULT now(),
    ativo_estado               boolean NOT NULL DEFAULT TRUE
);
CREATE INDEX ix_estado_pais_id ON estado(pais_id);

CREATE TABLE cidade (
    id_cidade                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_cidade                varchar(100) NOT NULL,
    codigo_ibge_cidade         varchar(10),
    estado_id                  bigint NOT NULL REFERENCES estado(id_estado),
    data_cadastro_cidade       timestamp with time zone NOT NULL DEFAULT now(),
    ultima_modificacao_cidade  timestamp with time zone NOT NULL DEFAULT now(),
    ativo_cidade               boolean NOT NULL DEFAULT TRUE
);
CREATE INDEX ix_cidade_estado_id ON cidade(estado_id);


-- =============================================================================
-- 2. CADASTROS DE APOIO
-- =============================================================================

CREATE TABLE categoria (
    id_categoria    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    categoria       varchar(60) NOT NULL,
    ativo_categoria boolean NOT NULL DEFAULT TRUE
);

CREATE TABLE marca (
    id_marca    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    marca       varchar(60) NOT NULL,
    ativo_marca boolean NOT NULL DEFAULT TRUE
);

CREATE TABLE unidade_medida (
    id_unidade_medida           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unidade_medida              varchar(255) NOT NULL,
    sigla_unidade_medida        varchar(5),
    fracionavel_unidade_medida  boolean NOT NULL DEFAULT FALSE,
    ativo_unidade_medida        boolean NOT NULL DEFAULT TRUE
);

CREATE TABLE forma_pagamento (
    id_forma_pagamento                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_forma_pagamento                varchar(100) NOT NULL,
    descricao_forma_pagamento           varchar(100) NOT NULL,
    data_cadastro_forma_pagamento       timestamp with time zone NOT NULL DEFAULT now(),
    ultima_modificacao_forma_pagamento  timestamp with time zone NOT NULL DEFAULT now(),
    ativo_forma_pagamento               boolean NOT NULL DEFAULT TRUE
);


-- =============================================================================
-- 3. PRODUTO
--    Aplica a regra obrigatória de venda por peso:
--    Subtotal = (peso_bruto - tara) * preco_kg
-- =============================================================================

CREATE TABLE produto (
    id_produto                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    produto                         varchar(255) NOT NULL,
    marca_id                        bigint NOT NULL REFERENCES marca(id_marca),
    unidade_medida_id               bigint NOT NULL REFERENCES unidade_medida(id_unidade_medida),
    categoria_id                    bigint REFERENCES categoria(id_categoria),
    valor_compra_produto            numeric(10,2) NOT NULL DEFAULT 0,
    valor_venda_produto             numeric(10,2) NOT NULL DEFAULT 0,
    quantidade_produto              numeric(15,4) NOT NULL DEFAULT 0,
    quantidade_minima_produto       numeric(15,4) NOT NULL DEFAULT 1,
    preco_kg_produto                numeric(10,2) NOT NULL DEFAULT 0,
    tara_produto                    numeric(10,3) NOT NULL DEFAULT 0,
    permite_fracionamento_produto   boolean NOT NULL DEFAULT FALSE,
    foto_url_produto                varchar(500),
    codigo_barras_produto           varchar(20),
    ativo_produto                   boolean NOT NULL DEFAULT TRUE
);
CREATE INDEX        ix_produto_marca_id          ON produto(marca_id);
CREATE INDEX        ix_produto_unidade_medida_id ON produto(unidade_medida_id);
CREATE INDEX        ix_produto_categoria_id      ON produto(categoria_id);
CREATE UNIQUE INDEX uq_produto_codigo_barras     ON produto(codigo_barras_produto)
    WHERE codigo_barras_produto IS NOT NULL;


-- =============================================================================
-- 4. PESSOAS  (suporta nacional ou estrangeiro, PF ou PJ)
-- =============================================================================

CREATE TABLE cliente (
    id_cliente              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente                 varchar(255) NOT NULL,
    tipo_pessoa_cliente     integer NOT NULL DEFAULT 0,           -- 0=Física, 1=Jurídica
    estrangeiro_cliente     boolean NOT NULL DEFAULT FALSE,
    cpf_cnpj_cliente        varchar(14),
    email_cliente           varchar(100),
    telefone_cliente        varchar(20),
    cidade_id               bigint REFERENCES cidade(id_cidade),
    limite_credito_cliente  numeric(10,2) NOT NULL DEFAULT 0,
    ativo_cliente           boolean NOT NULL DEFAULT TRUE
);
CREATE UNIQUE INDEX ix_cliente_cpf_cnpj_cliente ON cliente(cpf_cnpj_cliente);
CREATE INDEX        ix_cliente_cidade_id        ON cliente(cidade_id);

CREATE TABLE fornecedor (
    id_fornecedor           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fornecedor              varchar(255) NOT NULL,
    tipo_pessoa_fornecedor  integer NOT NULL DEFAULT 1,           -- 0=Física, 1=Jurídica
    estrangeiro_fornecedor  boolean NOT NULL DEFAULT FALSE,
    cpf_cnpj_fornecedor     varchar(14),
    email_fornecedor        varchar(255) NOT NULL,
    telefone_fornecedor     varchar(255) NOT NULL,
    cidade_id               bigint REFERENCES cidade(id_cidade),
    ativo_fornecedor        boolean NOT NULL DEFAULT TRUE
);
CREATE INDEX ix_fornecedor_cidade_id ON fornecedor(cidade_id);


-- =============================================================================
-- 5. OPERACIONAL — COMANDA / VENDA
--    Totais (subtotal, valor_total) NÃO são persistidos — derivados em runtime
--    para manter a 3ª Forma Normal.
-- =============================================================================

CREATE TABLE comanda (
    id_comanda               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_comanda           varchar(20) NOT NULL,
    cliente_id               bigint REFERENCES cliente(id_cliente),
    cliente_avulso_comanda   varchar(80),
    data_abertura_comanda    timestamp with time zone NOT NULL DEFAULT now(),
    data_fechamento_comanda  timestamp with time zone,
    status_comanda           integer NOT NULL DEFAULT 0,           -- 0=Aberta, 1=Fechada, 2=Cancelada
    ativo_comanda            boolean NOT NULL DEFAULT TRUE
);
CREATE INDEX ix_comanda_cliente_id ON comanda(cliente_id);

CREATE TABLE comanda_item (
    id_comanda_item              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comanda_id                   bigint NOT NULL REFERENCES comanda(id_comanda) ON DELETE CASCADE,
    produto_id                   bigint NOT NULL REFERENCES produto(id_produto),
    quantidade_comanda_item      numeric(14,3) NOT NULL DEFAULT 1,
    peso_bruto_comanda_item      numeric(10,3) NOT NULL DEFAULT 0,
    tara_comanda_item            numeric(10,3) NOT NULL DEFAULT 0,
    preco_unitario_comanda_item  numeric(12,2) NOT NULL DEFAULT 0,
    fracionado_comanda_item      boolean NOT NULL DEFAULT FALSE,
    observacao_comanda_item      varchar(255),
    ativo_comanda_item           boolean NOT NULL DEFAULT TRUE
);
CREATE INDEX ix_comanda_item_comanda_id ON comanda_item(comanda_id);
CREATE INDEX ix_comanda_item_produto_id ON comanda_item(produto_id);

CREATE TABLE venda (
    id_venda            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_venda          timestamp with time zone NOT NULL DEFAULT now(),
    comanda_id          bigint REFERENCES comanda(id_comanda),
    cliente_id          bigint REFERENCES cliente(id_cliente),
    forma_pagamento_id  bigint REFERENCES forma_pagamento(id_forma_pagamento),
    desconto_venda      numeric(12,2) NOT NULL DEFAULT 0,
    acrescimo_venda     numeric(12,2) NOT NULL DEFAULT 0,
    valor_pago_venda    numeric(12,2) NOT NULL DEFAULT 0,
    status_venda        integer NOT NULL DEFAULT 0,                -- 0=Concluída, 1=Cancelada
    ativo_venda         boolean NOT NULL DEFAULT TRUE
);
CREATE INDEX ix_venda_comanda_id         ON venda(comanda_id);
CREATE INDEX ix_venda_cliente_id         ON venda(cliente_id);
CREATE INDEX ix_venda_forma_pagamento_id ON venda(forma_pagamento_id);

CREATE TABLE venda_item (
    id_venda_item              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venda_id                   bigint NOT NULL REFERENCES venda(id_venda) ON DELETE CASCADE,
    produto_id                 bigint NOT NULL REFERENCES produto(id_produto),
    quantidade_venda_item      numeric(14,3) NOT NULL DEFAULT 1,
    peso_bruto_venda_item      numeric(10,3) NOT NULL DEFAULT 0,
    tara_venda_item            numeric(10,3) NOT NULL DEFAULT 0,
    preco_unitario_venda_item  numeric(12,2) NOT NULL DEFAULT 0,
    fracionado_venda_item      boolean NOT NULL DEFAULT FALSE,
    observacao_venda_item      varchar(255),
    ativo_venda_item           boolean NOT NULL DEFAULT TRUE
);
CREATE INDEX ix_venda_item_venda_id   ON venda_item(venda_id);
CREATE INDEX ix_venda_item_produto_id ON venda_item(produto_id);


-- =============================================================================
-- 6. SEED INICIAL — registros básicos para começar a operação
-- =============================================================================

INSERT INTO categoria (id_categoria, categoria, ativo_categoria) VALUES
    (1, 'Pratos Quentes', TRUE),
    (2, 'Bebidas',        TRUE),
    (3, 'Sobremesas',     TRUE);

INSERT INTO marca (id_marca, marca, ativo_marca) VALUES
    (1, 'Casa',      TRUE),
    (2, 'Coca-Cola', TRUE);

INSERT INTO unidade_medida (id_unidade_medida, unidade_medida, sigla_unidade_medida, fracionavel_unidade_medida, ativo_unidade_medida) VALUES
    (1, 'Unidade',    'UN', FALSE, TRUE),
    (2, 'Quilograma', 'KG', TRUE,  TRUE),
    (3, 'Litro',      'LT', TRUE,  TRUE);

-- Ajusta sequences depois do seed com IDs explícitos
SELECT setval(pg_get_serial_sequence('categoria',      'id_categoria'),      (SELECT COALESCE(MAX(id_categoria), 0)      FROM categoria));
SELECT setval(pg_get_serial_sequence('marca',          'id_marca'),          (SELECT COALESCE(MAX(id_marca), 0)          FROM marca));
SELECT setval(pg_get_serial_sequence('unidade_medida', 'id_unidade_medida'), (SELECT COALESCE(MAX(id_unidade_medida), 0) FROM unidade_medida));
